[OT171-40]  Testimonials integration
alkemyTech/OT171-swift-client pull request #31
Opened 2022-04-07 00:50 UTC by frannasich

- TestimonialsList, TestimonialsResponse and TestimonialsService added
- override deleted
- Class TestimonialsViewModel added
- cellForItemAt and didSelected Testimonials updated
- Fixed some errors of navigation in Splash
- Add condition to Hide Testimonials section

**comments:** Splash contains errors... LogInViewController is not show anymore

https://user-images.githubusercontent.com/80861248/162098257-716643b2-f4d7-489c-b3be-3d2158e7c36d.mov

### Jira Ticket
[OT171-40](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT171/boards/247?modal=detail&selectedIssue=OT171-40)

2022-04-08 04:03 UTC, gapoj requested changes
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-04-08 at 00 56 38](https://user-images.githubusercontent.com/8963285/162359861-9b1412ea-e1cd-419e-a869-b47118709997.png)
the story saids "En caso que el listado sea vacío, se deberá ocultar dicha sección" but when you don't have data it looks that the screenshot above

2022-04-08 04:07 UTC, gapoj commented
another thing you are not actually showing the testimony only the picture and the name of the person giving the testimony, this is a detail but since you are already will have to fix things

2022-04-08 04:10 UTC, frannasich commented
> another thing you are not actually showing the testimony only the picture and the name of the person giving the testimony, this is a detail but since you are already will have to fix things

![image](https://user-images.githubusercontent.com/80861248/162360826-049a5897-d059-459a-aa1e-b6994642e112.jpeg)

2022-04-08 04:16 UTC, gapoj commented on SomosMasApp/SomosMasApp/App/Shared/Modules/Home/Controller/HomeViewController.swift
> +            } else if indexPath.row == sliderViewModel?.getTestimonialsCount() && sliderViewModel?.getTestimonialsCount() == 0 {
- please take out this 
-  read the documentation so you understand when func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell  is called
- you should hide the entire section
- if you already are hiding the section be careful of the empty space, should be reduced 
- if yo have so many lines of code in a case you should separate this in a function

2022-04-11 18:09 UTC, gapoj approved these changes

2022-04-11 18:10 UTC, merged