[OT171-21]Sign Up view design
alkemyTech/OT171-swift-client pull request #7
Opened 2022-03-17 19:33 UTC by frannasich

### **Sign up view design added to the project**

- Added SignUpViewController with his xib
- Logo added to the view
- Placeholder added to the Mails label
- View labels conected with Controller

![Captura de Pantalla 2022-03-17 a la(s) 16 31 30](https://user-images.githubusercontent.com/80861248/158881315-f9b0cd69-6455-4637-8c8c-a76700f35aa2.png)

### **Jira Ticket**
OT171-21

2022-03-17 19:35 UTC, frannasich commented
I had to re-create another branch and make a pull request... is there a problem with deleting OT171-21_sign_up_view?

2022-03-18 02:01 UTC, gapoj commented
missing the name field on the form

2022-03-18 02:03 UTC, gapoj commented
DS_Store should not be on the repo

2022-03-18 02:32 UTC, frannasich commented
Ds_Store was pulled from the main

2022-03-18 13:51 UTC, frannasich commented
Sign up view is update

2022-03-21 01:39 UTC, gapoj requested changes
You should made only the requested changes, you should not affect the navigation

2022-03-21 01:39 UTC, gapoj commented on SomosMasApp/SomosMasApp/Info.plist
> -					<key>UISceneStoryboardFile</key>
why?

2022-03-21 17:21 UTC, merged